In [2]:
# kết nối vói drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# load dataset từ file csv
import pandas as pd

data_path = "/content/drive/MyDrive/NLP/mid_term/data.csv"
df = pd.read_csv(data_path)

In [3]:
df.head()

Title  \
0  Tại sao phụ nữ đòi bình đẳng nhưng bắt đàn ông...   
1  Capello: 'Guardiola mất nhiều Champions League...   
2  Xe ga sang xịn của ông lớn Trung Quốc: Thiết k...   
3          Không gian mở phong cách Hàn tại Gem Park   
4                  21 thanh niên hỗn chiến trong đêm   

                                                 URL  \
0  https://vnexpress.net/tai-sao-phu-nu-doi-binh-...   
1  https://vnexpress.net/capello-guardiola-mat-nh...   
2  https://kenh14.vn/xe-ga-sang-xin-cua-ong-lon-t...   
3  https://vnexpress.net/khong-gian-mo-phong-cach...   
4  https://vnexpress.net/21-thanh-nien-hon-chien-...   

                                           sub_title  \
0  "Quy tắc số 1" của Minh An khi hẹn hò là đàn ô...   
1  AnhTheo cựu HLV Fabio Capello, Pep Guardiola p...   
2  Không chỉ sở hữu mức giá ngang ngửa Honda Wave...   
3  Hải PhòngToàn bộ khu tiện ích tại Gem Park đượ...   
4  Nghệ AnHai nhóm thanh niên ở huyện Đô Lương do...   

                                             Content                   Author  \
0  "Làm gì có bình đẳng thực sự. Phụ nữ vẫn chịu ...               Phan Dương   
1  "Bạn có biết tôi không thích điều gì ở Guardio...  Thanh Quý(theoEl Mundo)   
2  Paifang Motorcycle (PFMoto) – thương hiệu xe m...                Minh Ngọc   
3  Hướng đến việc nâng cao trải nghiệm sống của c...                 Song Anh   
4  Ngày 11/3, Phòng Cảnh sát hình sự (Công an tỉn...                 Đức Hùng   

    Tag  
0  real  
1  real  
2  fake  
3  real  
4  real

In [4]:
# loại bỏ các columns ko cần thiết
df.drop(['URL', 'Author'], axis=1, inplace=True)

In [5]:
# chuyển fake and real sang 0 1
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df['Tag'] = encoder.fit_transform(df['Tag'])

In [6]:
df.head()

Title  \
0  Tại sao phụ nữ đòi bình đẳng nhưng bắt đàn ông...   
1  Capello: 'Guardiola mất nhiều Champions League...   
2  Xe ga sang xịn của ông lớn Trung Quốc: Thiết k...   
3          Không gian mở phong cách Hàn tại Gem Park   
4                  21 thanh niên hỗn chiến trong đêm   

                                           sub_title  \
0  "Quy tắc số 1" của Minh An khi hẹn hò là đàn ô...   
1  AnhTheo cựu HLV Fabio Capello, Pep Guardiola p...   
2  Không chỉ sở hữu mức giá ngang ngửa Honda Wave...   
3  Hải PhòngToàn bộ khu tiện ích tại Gem Park đượ...   
4  Nghệ AnHai nhóm thanh niên ở huyện Đô Lương do...   

                                             Content  Tag  
0  "Làm gì có bình đẳng thực sự. Phụ nữ vẫn chịu ...    1  
1  "Bạn có biết tôi không thích điều gì ở Guardio...    1  
2  Paifang Motorcycle (PFMoto) – thương hiệu xe m...    0  
3  Hướng đến việc nâng cao trải nghiệm sống của c...    1  
4  Ngày 11/3, Phòng Cảnh sát hình sự (Công an tỉn...    1

In [45]:
print(len(df))
print(len(df[df['Tag'] == 1]))

1226
639


In [8]:
# cài đặt thư viện
!pip install underthesea

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.9/20.9 MB 57.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 657.8/657.8 kB 33.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 53.7 MB/s eta 0:00:00


In [7]:
# ------ Pre-processing ###
from underthesea import word_tokenize
import re
import numpy as np

# convert data
df[['Title', 'sub_title', 'Content']] = df[['Title', 'sub_title', 'Content']].astype(str)

In [8]:
def clean_text(text):
  text = text.lower()
  text = re.sub(r'\W', ' ', text)
  text = re.sub(r'\s+', ' ', text)
  return text

def tokenize_text(text):
  return word_tokenize(text, format='text')

In [9]:
# BoWs
def build_vocab(data_col):
  vocab = {}
  for text in data_col:
    for word in text.split():
      if word not in vocab.keys():
        vocab[word] = 1
      else:
        vocab[word] += 1
  return vocab

In [23]:
df['tokenized_title'] = df['Title'].apply(clean_text).apply(tokenize_text)
df['tokenized_sub_title'] = df['sub_title'].apply(clean_text).apply(tokenize_text)
df['tokenized_content'] = df['Content'].apply(clean_text).apply(tokenize_text)

In [24]:
df['combine_token'] = df['tokenized_title'] + ' ' + df['tokenized_sub_title'] + ' ' + df['tokenized_content']

In [25]:
df.head()

Title  \
0  Tại sao phụ nữ đòi bình đẳng nhưng bắt đàn ông...   
1  Capello: 'Guardiola mất nhiều Champions League...   
2  Xe ga sang xịn của ông lớn Trung Quốc: Thiết k...   
3          Không gian mở phong cách Hàn tại Gem Park   
4                  21 thanh niên hỗn chiến trong đêm   

                                           sub_title  \
0  "Quy tắc số 1" của Minh An khi hẹn hò là đàn ô...   
1  AnhTheo cựu HLV Fabio Capello, Pep Guardiola p...   
2  Không chỉ sở hữu mức giá ngang ngửa Honda Wave...   
3  Hải PhòngToàn bộ khu tiện ích tại Gem Park đượ...   
4  Nghệ AnHai nhóm thanh niên ở huyện Đô Lương do...   

                                             Content  Tag  \
0  "Làm gì có bình đẳng thực sự. Phụ nữ vẫn chịu ...    1   
1  "Bạn có biết tôi không thích điều gì ở Guardio...    1   
2  Paifang Motorcycle (PFMoto) – thương hiệu xe m...    0   
3  Hướng đến việc nâng cao trải nghiệm sống của c...    1   
4  Ngày 11/3, Phòng Cảnh sát hình sự (Công an tỉn...    1   

                                     tokenized_title  \
0  tại_sao phụ_nữ đòi bình_đẳng nhưng bắt đàn_ông...   
1  capello guardiola mất nhiều champions_league v...   
2  xe ga sang xịn của ông lớn trung_quốc thiết_kế...   
3          không_gian mở phong_cách hàn tại gem park   
4                  21 thanh_niên hỗn_chiến trong đêm   

                                 tokenized_sub_title  \
0  quy_tắc số 1 của minh_an khi hẹn_hò là đàn_ông...   
1  anhtheo cựu hlv fabio capello pep guardiola ph...   
2  không_chỉ sở_hữu mức giá ngang ngửa honda wave...   
3  hải_phòngtoàn bộ khu tiện_ích tại gem park đượ...   
4  nghệ anhai nhóm thanh_niên ở huyện đô_lương do...   

                                   tokenized_content  \
0  làm gì có bình_đẳng thực_sự phụ_nữ vẫn chịu nh...   
1  bạn có biết tôi không thích điều gì ở guardiol...   
2  paifang motorcycle pfmoto thương_hiệu xe_máy đ...   
3  hướng đến việc nâng cao trải_nghiệm sống của c...   
4  ngày 11 3 phòng cảnh_sát hình_sự công_an tỉnh ...   

                                       combine_token  
0  tại_sao phụ_nữ đòi bình_đẳng nhưng bắt đàn_ông...  
1  capello guardiola mất nhiều champions_league v...  
2  xe ga sang xịn của ông lớn trung_quốc thiết_kế...  
3  không_gian mở phong_cách hàn tại gem park hải_...  
4  21 thanh_niên hỗn_chiến trong đêm nghệ anhai n...

In [46]:
# save new df
df.to_csv('/content/drive/MyDrive/NLP/mid_term/processed_data.csv', index=False)

In [26]:
vocab = build_vocab(df['combine_token'])
print(vocab)
print(len(vocab))

{'tại_sao': 69, 'phụ_nữ': 303, 'đòi': 46, 'bình_đẳng': 27, 'nhưng': 2352, 'bắt': 141, 'đàn_ông': 179, 'làm': 1952, 'trụ_cột': 46, 'quy_tắc': 29, 'số': 971, '1': 1676, 'của': 10626, 'minh_an': 1, 'khi': 4955, 'hẹn_hò': 85, 'là': 8227, 'phải': 2069, 'thanh_toán': 76, 'ít_nhất': 115, 'năm': 4016, 'buổi': 333, 'đầu_tiên': 468, 'từ': 3981, 'thứ': 872, '6': 789, 'cô': 1341, 'có_thể': 2700, 'chia_sẻ': 821, 'một': 5921, 'phần': 596, 'nhỏ': 504, 'gì': 679, 'có': 7157, 'thực_sự': 224, 'vẫn': 1365, 'chịu': 243, 'nhiều': 3972, 'bất_công': 13, 'chi': 118, 'hơn': 3081, 'mới': 1778, 'công_bằng': 43, 'gái': 310, 'ở': 3973, 'tp': 832, 'hcm': 625, 'lập_luận': 13, 'cho': 6565, 'rằng': 1230, 'nam_giới': 94, 'thu_nhập': 200, 'trung_bình': 145, 'cao': 1361, 'trong': 8461, 'đầu_tư': 943, 'vào': 3240, 'ngoại_hình': 47, 'trang_điểm': 28, 'váy': 53, 'áo': 152, 'đến': 4168, 'tóc': 208, 'để': 4630, 'đáp_ứng': 170, 'kỳ_vọng': 148, 'xã_hội': 736, 'việc': 1988, 'trả': 256, 'tiền': 1124, 'cũng': 3208, 'cách': 1041, '

In [27]:
# model bow
def bow_feature(data_col, vocab):
  X = []
  for text in data_col:
    vector = []
    for word in vocab:
      if word in text.split():
        vector.append(1)
      else:
        vector.append(0)
    X.append(vector)
  return np.asarray(X)

In [17]:
X = bow_feature(df['combine_token'], vocab)

In [18]:
# save BoWs vector
np.save('/content/drive/MyDrive/NLP/mid_term/bow_matrix.npy', X)

In [11]:
# code to load X
# X = np.load('/content/drive/MyDrive/NLP/mid_term/bow_matrix.npy')

In [12]:
print(type(X))
print(X)

<class 'numpy.ndarray'>
[[1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 1]]


In [20]:
# save vocab in order to load when restart code
import pickle

with open('/content/drive/MyDrive/NLP/mid_term/vocab.pkl', 'wb') as f:
  pickle.dump(vocab, f)

In [14]:
# code to load vocab from drive
# import pickle

# with open('/content/drive/MyDrive/NLP/mid_term/vocab.pkl', 'rb') as f:
#   vocab = pickle.load(f)

In [21]:
!pip install sklearn

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [15]:
# <----------- Model with bow vector---------------
from sklearn.model_selection import train_test_split
y = df['Tag']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [17]:
# -------------------------
#       Naive Bayes       #
# -------------------------

def naive_bayes_model(X_train, y_train):
  nb_model = MultinomialNB()
  nb_model.fit(X_train, y_train)
  return nb_model

In [18]:
# ---------------------------------
#       Logistic Regression       #
# ---------------------------------

def logistic_regression_model(X_train, y_train):
  lr_model = LogisticRegression()
  lr_model.fit(X_train, y_train)
  return lr_model

In [19]:
# --------------------------
#       Decision Tree      #
# --------------------------

def decision_tree_model(X_train, y_train):
  dt_model = DecisionTreeClassifier()
  dt_model.fit(X_train, y_train)
  return dt_model

In [20]:
# Running model

# naive bayes
nb_model = naive_bayes_model(X_train, y_train)
nb_pred = nb_model.predict(X_test)
print(f"Naive Bayes Accuracy: {accuracy_score(y_test, nb_pred)*100: .3f}")
print(f"Naive Bayes Precision: {precision_score(y_test, nb_pred)*100: .3f}")
print(f"Naive Bayes Recall: {recall_score(y_test, nb_pred)*100: .3f}")
print(f"Naive Bayes F1-score: {f1_score(y_test,nb_pred)*100: .3f}")
print('\n')

# logistic regression
lr_model = logistic_regression_model(X_train, y_train)
lr_pred = lr_model.predict(X_test)
print(f"Logistic Regression Accuracy: {accuracy_score(y_test, lr_pred)*100: .3f}")
print(f"Logistic Regression Precision: {precision_score(y_test, lr_pred)*100: .3f}")
print(f"Logistic Regression Recall: {recall_score(y_test, lr_pred)*100: .3f}")
print(f"Logistic Regression F1-score: {f1_score(y_test,lr_pred)*100: .3f}")
print('\n')

# decision tree
dt_model = decision_tree_model(X_train, y_train)
dt_pred = dt_model.predict(X_test)
print(f"Decision Tree Accuracy: {accuracy_score(y_test, dt_pred)*100: .3f}")
print(f"Decision Tree Precision: {precision_score(y_test, dt_pred)*100: .3f}")
print(f"Decision Tree Recall: {recall_score(y_test, dt_pred)*100: .3f}")
print(f"Decision Tree F1-score: {f1_score(y_test,dt_pred)*100: .3f}")

Naive Bayes Accuracy:  84.959
Naive Bayes Precision:  86.207
Naive Bayes Recall:  82.645
Naive Bayes F1-score:  84.388


Logistic Regression Accuracy:  90.244
Logistic Regression Precision:  87.023
Logistic Regression Recall:  94.215
Logistic Regression F1-score:  90.476


Decision Tree Accuracy:  84.553
Decision Tree Precision:  83.200
Decision Tree Recall:  85.950
Decision Tree F1-score:  84.553


In [28]:
# test out side sentence

# this is fake news which was created by Grok - 3
sentence_test = "Trong một diễn biến bất ngờ, một thị trấn nhỏ ở miền Trung Việt Nam " \
                "được cho là đã bị robot điều khiển bởi AI chiếm lĩnh vào tối qua. " \
                "Các nhân chứng kể lại rằng những cỗ máy này xuất hiện từ một phòng thí nghiệm bí mật, " \
                "phát ra những âm thanh kỳ lạ bằng mã nhị phân. " \
                "Người dân địa phương, anh Nguyễn Văn A, cho biết: 'Chúng cứ lặp lại 0101, " \
                "rồi bắt đầu sửa chữa ổ gà trên đường!' " \
                "Chính quyền địa phương đang bối rối, " \
                "nhưng một số người nghi ngờ đây là chiêu trò quảng bá của TechCorpVN, " \
                "một công ty nổi tiếng với những sáng tạo độc đáo. " \
                "Những robot này, được trang bị tia laser và bánh xe, " \
                "đã bắt đầu tổ chức một cuộc họp thị trấn do robot dẫn dắt. " \
                "Thông tin chi tiết sẽ được cập nhật khi câu chuyện kỳ lạ này tiếp diễn."

sentence_test = clean_text(sentence_test)
token_test = tokenize_text(sentence_test)
vector_token_test = bow_feature([token_test], vocab)
print(vector_token_test)

# use 3 model to predict

# naive bayes
nb_prediction = nb_model.predict(vector_token_test)
print(f"Naive Bayes Prediction: {nb_prediction}")

# logistic regression
lr_prediction = lr_model.predict(vector_token_test)
print(f"Logistic Regression Prediction: {lr_prediction}")

# decision tree
dt_prediction = dt_model.predict(vector_token_test)
print(f"Decision Tree Prediction: {dt_prediction}")

[[0 0 0 ... 0 0 0]]
Naive Bayes Prediction: [0]
Logistic Regression Prediction: [1]
Decision Tree Prediction: [0]


In [29]:
# this content is real which was created by grok - 3
test_content = "Trong một sự kiện được tổ chức tại Hà Nội vào ngày 14/3/2025, " \
          "VinFast đã chính thức ra mắt dòng xe điện mới với công nghệ tiên tiến. " \
          "Chiếc xe này được trang bị pin có khả năng sạc nhanh trong 15 phút, " \
          "cho phép di chuyển quãng đường lên đến 500 km chỉ trong một lần sạc. " \
          "Ông Nguyễn Văn B, đại diện công ty, cho biết: 'Đây là bước tiến lớn, " \
          "nhằm mang lại giải pháp giao thông bền vững cho người Việt.' " \
          "Các chuyên gia nhận định rằng sản phẩm này có thể cạnh tranh với Tesla, " \
          "đặc biệt nhờ giá thành hợp lý và mạng lưới trạm sạc đang mở rộng. " \
          "Người dân tại sự kiện tỏ ra phấn khích, " \
          "với nhiều người đăng ký lái thử ngay trong ngày ra mắt. " \
          "VinFast dự kiến sẽ xuất khẩu mẫu xe này sang thị trường quốc tế vào cuối năm 2025."

test_content = clean_text(test_content)
token = tokenize_text(test_content)
vector = bow_feature([token], vocab)
print(vector)

# use 3 model to predict

# naive bayes
nb_prediction = nb_model.predict(vector)
print(f"Naive Bayes Prediction: {nb_prediction}")

# logistic regression
lr_prediction = lr_model.predict(vector)
print(f"Logistic Regression Prediction: {lr_prediction}")

# decision tree
dt_prediction = dt_model.predict(vector)
print(f"Decision Tree Prediction: {dt_prediction}")

[[0 0 0 ... 0 0 0]]
Naive Bayes Prediction: [1]
Logistic Regression Prediction: [1]
Decision Tree Prediction: [1]


# Use TF-IDF Vector for feature training


In [34]:
from collections import Counter

vocab_term = list(vocab.keys())

# Step 1: Compute Term of Frequence
# tf = frequence of a term / total token
def compute_tf(doc, vocab_term):
  token_counts = Counter(doc.split())
  tf = {term: token_counts.get(term, 0)/ len(doc) for term in vocab_term}
  return tf

# Step 2: Compute Inverse Document Frequency
# idf = length of docs / number of doc contain term
def compute_idf(docs, vocab_term):
  num_docs = len(docs)
  idf = {}
  for term in vocab_term:
    num_docs_with_term = sum(1 for doc in docs if term in doc)
    idf[term] = np.log(num_docs / num_docs_with_term) if num_docs_with_term > 0 else 0
  return idf

# Step 3: Compute TF-IDF
# TF-IDF = TF * IDF
def compute_tf_idf(tf, idf, vocab_term):
  tf_idf = np.zeros(len(vocab_term))
  for i, term in enumerate(vocab_term):
    tf_idf[i] = tf[term] * idf[term]
  return tf_idf

In [28]:
tf_list = [compute_tf(doc, vocab_term) for doc in df['combine_token']]
print(tf_list)

In [35]:
idf = compute_idf(df['combine_token'], vocab_term)
print(idf)

{'tại_sao': 3.0861604257610074, 'phụ_nữ': 2.2831983791938555, 'đòi': 2.4019819151838226, 'bình_đẳng': 4.4034619153939465, 'nhưng': 0.4599402429064296, 'bắt': 1.0953549567978031, 'đàn_ông': 2.5682173342261527, 'làm': 0.41695005797506135, 'trụ_cột': 3.6150045550296763, 'quy_tắc': 4.115779842942166, 'số': 0.19479709614254773, '1': 0.09939682218977693, 'của': 0.06138959622709758, 'minh_an': 7.111512116496157, 'khi': 0.11026649442668082, 'hẹn_hò': 3.4479504703665103, 'là': 0.04334011610811499, 'phải': 0.5239621016713607, 'thanh_toán': 3.261364514786098, 'ít_nhất': 2.5368011379927737, 'năm': 0.28063788184997723, 'buổi': 1.7502199507867315, 'đầu_tiên': 1.3749398190169648, 'từ': 0.11574596019130637, 'thứ': 0.4509369666564707, '6': 0.3949173429751786, 'cô': 0.17128964737651808, 'có_thể': 0.418188448226208, 'chia_sẻ': 1.1582687822083724, 'một': 0.10844665770969476, 'phần': 0.7693906977750053, 'nhỏ': 1.324614735129449, 'gì': 1.3846643689089595, 'có': 0.049320484209600744, 'thực_sự': 2.03633830126

In [36]:
# compute tf-idf
tf_idf_vector = np.array([compute_tf_idf(tf, idf, vocab_term) for tf in tf_list])
print(tf_idf_vector)

[[0.00047648 0.00564014 0.00037085 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.00244298 0.00244298 0.00244298]]


In [37]:
# save vector tf-idf
X_tf_idf = tf_idf_vector
np.save('/content/drive/MyDrive/NLP/mid_term/tf_idf.npy', X_tf_idf)

In [ ]:
# load vector tf-idf
# X_tf_idf = np.load('/content/drive/MyDrive/NLP/mid_term/tf_idf.npy')

In [38]:
# <------ Model with tf-idf vector ---
from sklearn.model_selection import train_test_split
y = df['Tag']
X_train, X_test, y_train, y_test = train_test_split(X_tf_idf, y, test_size=0.2, random_state=42)

In [39]:
# Running model

# naive bayes
nb_model_tfidf = naive_bayes_model(X_train, y_train)
nb_pred_tfidf = nb_model_tfidf.predict(X_test)
print(f"Naive Bayes Accuracy: {accuracy_score(y_test, nb_pred_tfidf)*100: .3f}")
print(f"Naive Bayes Precision: {precision_score(y_test, nb_pred_tfidf)*100: .3f}")
print(f"Naive Bayes Recall: {recall_score(y_test, nb_pred_tfidf)*100: .3f}")
print(f"Naive Bayes F1-score: {f1_score(y_test,nb_pred_tfidf)*100: .3f}")
print('\n')

# logistic regression
lr_model_tfidf = logistic_regression_model(X_train, y_train)
lr_pred_tfidf = lr_model_tfidf.predict(X_test)
print(f"Logistic Regression Accuracy: {accuracy_score(y_test, lr_pred_tfidf)*100: .3f}")
print(f"Logistic Regression Precision: {precision_score(y_test, lr_pred_tfidf)*100: .3f}")
print(f"Logistic Regression Recall: {recall_score(y_test, lr_pred_tfidf)*100: .3f}")
print(f"Logistic Regression F1-score: {f1_score(y_test,lr_pred_tfidf)*100: .3f}")
print('\n')

# decision tree
dt_model_tfidf = decision_tree_model(X_train, y_train)
dt_pred_tfidf = dt_model_tfidf.predict(X_test)
print(f"Decision Tree Accuracy: {accuracy_score(y_test, dt_pred_tfidf)*100: .3f}")
print(f"Decision Tree Precision: {precision_score(y_test, dt_pred_tfidf)*100: .3f}")
print(f"Decision Tree Recall: {recall_score(y_test, dt_pred_tfidf)*100: .3f}")
print(f"Decision Tree F1-score: {f1_score(y_test,dt_pred_tfidf)*100: .3f}")

Naive Bayes Accuracy:  49.187
Naive Bayes Precision:  49.187
Naive Bayes Recall:  100.000
Naive Bayes F1-score:  65.940


Logistic Regression Accuracy:  49.187
Logistic Regression Precision:  49.187
Logistic Regression Recall:  100.000
Logistic Regression F1-score:  65.940


Decision Tree Accuracy:  83.333
Decision Tree Precision:  82.258
Decision Tree Recall:  84.298
Decision Tree F1-score:  83.265


# Naive Bayes
- Designed for count data (e.g., BoW), where features are non-negative integers.
- TF-IDF uses floating-point values (0 to 1 scaled by IDF), which can weaken the multinomial assumption. The continuous nature of TF-IDF might confuse the probability estimates.

# Logistic Regression
- Works with continuous features, but TF-IDF’s normalization (TF) and IDF weighting might reduce feature variance compared to BoW’s raw counts.
- If BoW had higher variance (larger counts for frequent terms), Logistic Regression could separate classes better.
